# Parameters specific to the hardware of the Manta drone
#
# Thruster placement from above
#   Vertical: 1, 2, 5, 6
#   Horizontal: 0, 3, 4, 7

#       _______                        _______
#     /         \        ____        /         \
#   /             \     /____\     /             \
#  /      7↗        \ _|______|_ /      ↖ 0       \
#  \                                              /
#   \                                            /
#     \          6                  1          /
#      \                                      /
#       |                                    |
#       |                                    | 
#      /                                      \
#     /          5                  2          \
#   /                                            \
#  /                  __________                  \
#  \       4↘       /            \       ↙ 3      /
#   \             /                \             /
#     \ _______ /                    \ _______ /


                               
physical:
  mass_kg: 0
  displacement_m3: 0
  center_of_mass: [0, 0, 0]
  center_of_buoyancy: [0, 0, 0]
  drag_coefficients: [80, 80, 204, 1, 1, 1]
  thruster_layout:
    [[-0.70711, 0.70711, 0],
     [ 0.00000, 0.00000, 1],
     [ 0.00000, 0.00000, 1],
     [-0.70711,-0.70711, 0],
     [ 0.70711,-0.70711, 0],
     [ 0.00000, 0.00000, 1],
     [ 0.00000, 0.00000, 1],
     [ 0.70711, 0.70711, 0]]
  thruster_positions:
    [[ 0.20506,  0.20506, 0],
     [ 0.12070,  0.12070, 0],
     [ 0.12070, -0.12070, 0],
     [ 0.20506, -0.20506, 0],
     [-0.20506, -0.20506, 0],
     [-0.12070, -0.12070, 0],
     [-0.12070,  0.12070, 0],
     [-0.20506,  0.20506, 0]]

propulsion:
  dofs:
    num: 6
    which:
      surge: true
      sway:  true
      heave: true
      roll:  true
      pitch: true
      yaw:   true
  thrusters:
    num: 8
    map: [0, 1, 2, 3, 4, 5, 6, 7]
    direction: [1, 1, 1, 1, 1, 1, 1, 1]
    configuration_matrix:
      [[ 0.70711,  0.00000,  0.00000, -0.70711, -0.70711,  0.00000,  0.00000, 0.70711], # Surge
       [-0.70711,  0.00000,  0.00000, -0.70711,  0.70711,  0.00000,  0.00000, 0.70711], # Sway
       [ 0.00000,  1.00000,  1.00000,  0.00000,  0.00000,  1.00000,  1.00000, 0.00000], # Heave
       [ 0.00000,  0.12000,  0.12000,  0.00000,  0.00000, -0.12000, -0.12000, 0.00000], # Roll
       [ 0.00000, -0.12000,  0.12000,  0.00000,  0.00000,  0.12000, -0.12000, 0.00000], # Pitch
       [-0.29000, -0.00000, -0.00000,  0.29000, -0.29000,  0.00000,  0.00000, 0.29000]] # Yaw
  command:
    wrench:
      max:     [33.9, 33.9, 48.0, 7.6, 3.2, 9.9]
      scaling: [ 0.4,  0.4,  0.6, 0.3, 0.7, 0.4]

controller:
  circleOfAcceptance: 0.10
  frequency: 40
  position_gain: 0.3 #5.0
  attitude_gain: 0.4 #2.5
  velocity_gain: 0.7 #0.4
  integral_gain: 0.0 #0.3

# Update the computer name when wrapping up
computer: 'rpi'
